from django.urls import path, include
from rest_framework.routers import DefaultRouter
# *** THIS IS THE CRUCIAL LINE: importing 'views' for the token endpoint ***
from rest_framework.authtoken import views 
from .views import BookList, BookViewSet

# Create a router instance
router = DefaultRouter()

# Register the ViewSet with the router. 
# The prefix is 'books_all' and the basename is 'book_all'
router.register(r'books_all', BookViewSet, basename='book_all')

app_name = 'api'

urlpatterns = [
    # 1. Existing Route for the BookList View
    path('books/', BookList.as_view(), name='book-list'),

    # 2. Include the routes generated by the router for CRUD operations
    path('', include(router.urls)),
    
    # 3. Endpoint for token retrieval (uses the imported 'views')
    path('auth/token/', views.obtain_auth_token)
]